In [ ]:
import numpy as np
import cmath

In [ ]:
# (AB)* = A*B*
# A*Bconjugate = Aconjugate*Bconjugate

In [ ]:
i = cmath.sqrt(-1)
a = np.matrix([[-i, 1],[1, i]])
a

matrix([[-0.-1.j,  1.+0.j],
        [ 1.+0.j,  0.+1.j]])

In [ ]:
b = np.matrix([[3, 2+i], [4, 1]])
astar = a.conjugate()
bstar = b.conjugate()
astar, bstar
c = np.matmul(astar, bstar)
c

matrix([[4.+3.j, 2.+2.j],
        [3.-4.j, 2.-2.j]])

In [ ]:
d = np.matmul(a, b)
dstar = d.conjugate()
dstar

matrix([[4.+3.j, 2.+2.j],
        [3.-4.j, 2.-2.j]])

In [ ]:
#Transpose
#(AB)Transpose = Atranspose.Btranspose

In [ ]:
atrans = a.transpose()
btrans= b.transpose()

abmul = np.matmul(a,b)

abtransmul = abmul.transpose()

atransbtransmul = np.matmul(btrans,atrans)

abtransmul,atransbtransmul


(matrix([[4.-3.j, 3.+4.j],
         [2.-2.j, 2.+2.j]]),
 matrix([[4.-3.j, 3.+4.j],
         [2.-2.j, 2.+2.j]]))

In [ ]:
# (A+B)Transpose = ATranspose + BTranspose

In [ ]:
c = (a+b).transpose()
c

matrix([[3.-1.j, 5.+0.j],
        [3.+1.j, 1.+1.j]])

In [ ]:
d = atrans+btrans

In [ ]:
c, d

(matrix([[3.-1.j, 5.+0.j],
         [3.+1.j, 1.+1.j]]),
 matrix([[3.-1.j, 5.+0.j],
         [3.+1.j, 1.+1.j]]))

# Trace of Matrix

In [ ]:
A = np.matrix([[1, 0, 0],[0, 2, 0],[0, 0, 3]])
B = np.matrix([[2, 5, 6], [7, 8, 10], [0, 1, 2]])

matrix([[1, 0, 0]])

In [ ]:
trace1 = 0
for i in range(len(A)):
  for j in range(len(A)):
    if i == j:
      trace1 = trace1 + A[i, j]
trace2 = 0
for i in range(len(B)):
  for j in range(len(B)):
    if i == j:
      trace2 = trace2 + B[i, j]
tracesum = trace1 + trace2
tracesum

18

In [ ]:
C=A+B
trace3 = 0
for i in range(len(C)):
  for j in range(len(C)):
    if i == j:
      trace3 = trace3 + C[i, j]
trace3

18

In [ ]:
# Inverse of a matrix

In [ ]:
X = np.matrix([[1, 2, 3], [4, 5, 6], [7, 2, 9]])
#inverse
Y = np.linalg.inv(X)

matrix([[ 33., -12.,  -3.],
        [  6., -12.,   6.],
        [-27.,  12.,  -3.]])

In [ ]:
# Adjoint matrix
np.linalg.det(X)*Y

In [ ]:
# Determinant of a matrix
np.linalg.det(X)

0.0

In [ ]:
# Rank of a matrix

In [49]:
rank = np.linalg.matrix_rank(X)
rank

2