In [ ]:
# Python code to demonstrate matrix operations
# importing numpy for matrix operations

import numpy

# initializing matrices
x = numpy.array([[2,-1], [3,-2], [4,1]])
y = numpy.array([[0,3,-4], [2,-1,1]])

In [ ]:
# using add() to add matrices
print ("The element wise addition of matrix is : ")
print (numpy.add(x,y))

The element wise addition of matrix is : 
[[ 8 10]
 [13 15]]


In [ ]:
# using subtract() to subtract matrices
print ("The element wise subtraction of matrix is : ")
print (numpy.subtract(x,y))

The element wise subtraction of matrix is : 
[[-6 -6]
 [-5 -5]]


In [ ]:
# using divide() to divide matrices
print ("The element wise division of matrix is : ")
print (numpy.divide(x,y))

The element wise division of matrix is : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [ ]:
# using multiply() to multiply matrices element wise
print ("The element wise multiplication of matrix is : ")
print (numpy.multiply(x,y))

In [ ]:
# using dot() to multiply matrices
print ("The product of matrices is : ")
print (numpy.dot(y,x))

The product of matrices is : 
[[ -7 -10]
 [  5   1]]


In [ ]:
# using "T" to transpose the matrix
print ("The transpose of given matrix is : ")
print (x.T)

The transpose of given matrix is : 
[[1 4]
 [2 5]]


In [ ]:
#Matrix 1
print("Enter details for matrix 1")
a_row=int(input("Enter number of rows:"))
a_col=int(input("Enter number of columns:"))
print()
#Matrix 2
print("Enter details for matrix 2")
b_row=int(input("Enter number of rows:"))
b_col=int(input("Enter number of columns:"))

# Initialize matrix 1
matrix1=[]
#Take input from user
print("Enter the entries row wise")
for i in range(a_row):
  a=[]
  for j in range(a_col):
    a.append(int(input()))
  matrix1.append(a)


# Initialize matrix
matrix2=[]
#Take input from user
print("Enter the entries row wise")
for i in range(b_row):
  a=[]
  for j in range(b_col):
    a.append(int(input()))
  matrix2.append(a)

# print matrix
print("\nMatrix 1")
for i in range(a_row):
  for j in range(a_col):
    print(matrix1[i][j],end=" ")
  print()

print("\nMatrix 2")
for i in range(b_row):
  for j in range(b_col):
    print(matrix2[i][j],end=" ")
  print()

Enter details for matrix 1
Enter number of rows:2
Enter number of columns:2
Enter the entries row wise
1
2
3
4
Enter details for matrix 2
Enter number of rows:2
Enter number of columns:2
Enter the entries row wise
5
6
7
8

Matrix 1
1 2 
3 4 

Matrix 2
5 6 
7 8 


In [ ]:
#Matrix 1
print("Enter details for matrix 1")
a_row=int(input("Enter number of rows:"))
a_col=int(input("Enter number of columns:"))
print()
#Matrix 2
print("Enter details for matrix 2")
b_row=int(input("Enter number of rows:"))
b_col=int(input("Enter number of columns:"))

if a_col == b_row:
  print("Enter the entries row wise for Matrix 1")
  #matrix_a = [[int(input(f"column {j+1} -> Enter {i+1} element:")) for j in range(a_col)] for i in range(a_row) ]

  print("Enter the entries row wise")
    for i in range(a_row):

      for j in range(a_col):
        a.append(int(input()))

In [ ]:
#Rank of Matrix
matrixA = numpy.array([[1, 2, 3 ],
                       [2, 1 , 4],
                       [3, 0, 5 ]])

print("The Rank of a Matrix: ", numpy.linalg.matrix_rank(matrixA))

The Rank of a Matrix:  2


**Eigen Vector & Eigen Values**

*linalg.eig(a)
- Compute the eigenvalues and right eigenvectors of a square array.

In [ ]:
import numpy as np

# create numpy 2d-array
m = np.array([[2, 2, 2],
              [2, 2, 2],
              [2, 2, 2]])

print("Printing the Original square array:\n", m)

# finding eigenvalues and eigenvectors
w, v = np.linalg.eig(m)

# printing eigen values
print("\nPrinting the Eigen values of the given square array:\n\n", w)

# printing eigen vectors
print("\nPrinting Right eigenvectors of the given square array:\n\n", v)

Printing the Original square array:
 [[2 2 2]
 [2 2 2]
 [2 2 2]]

Printing the Eigen values of the given square array:

 [-4.4408921e-16  6.0000000e+00  0.0000000e+00]

Printing Right eigenvectors of the given square array:

 [[-0.81649658  0.57735027  0.        ]
 [ 0.40824829  0.57735027 -0.70710678]
 [ 0.40824829  0.57735027  0.70710678]]


In [ ]:
import numpy as np
from numpy.linalg import eig

In [ ]:
a = np.array([[1, 2],
              [5, 4]])
w,v=eig(a)
print('E-value:\n', w)
print('E-vector:\n', v)

E-value:
 [-1.  6.]
E-vector:
 [[-0.70710678 -0.37139068]
 [ 0.70710678 -0.92847669]]


In [2]:
# Scalar operations on vector
import numpy as np
x=np.array([1,2,3])
print(2*x)
print(5+x)

[2 4 6]
[6 7 8]
