In [1]:
import numpy as np

In [3]:
v=np.array([2,4,7])

In [4]:
v

array([2, 4, 7])

In [5]:
u=np.array([1,2,3])

In [6]:
u+v

array([ 3,  6, 10])

In [8]:
u-v

array([-1, -2, -4])

In [10]:
u.dot(v)

31

In [11]:
b=np.cross(u,v)
b

array([ 2, -1,  0])

In [12]:
from numpy import linalg as LA

In [29]:
a = np.arange(9) - 4

a

array([-4, -3, -2, -1,  0,  1,  2,  3,  4])

In [30]:
LA.norm(a, 0)

8.0

In [36]:
LA.norm(a,1000)

inf

In [17]:
LA.norm(a)

7.745966692414834

In [19]:
b = a.reshape((3, 3))
b

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [37]:
LA.norm(a, 1)

20.0

In [38]:
LA.norm(a, 2)

7.745966692414834

In [39]:
a = np.arange(16) - 1

a

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])